# snd_soc_wsa883x: enable power saving for speaker amplifier codec
options snd_soc_wsa883x power_save=1

# snd_soc_wcd938x: enable power saving for audio codec
options snd_soc_wcd938x power_save=1
