[General]
EnableNetworkConfiguration=false
RoamThreshold=-75
RoamThreshold5G=-80
RoamThreshold6G=-80
AddressRandomization=once
ManagementFrameProtection=2

[Scan]
DisablePeriodicScan=false
InitialPeriodicScanInterval=10
MaximumPeriodicScanInterval=300

[Rank]
BandModifier5Ghz=2.0
BandModifier6Ghz=3.0
